- name: update Debian
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: update CentOS
  dnf:
    update_only: true
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Print the gateway for each host when defined
  debug:
    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
  when: ansible_default_ipv4.gateway is defined

- name: generate sshd config file
  tags: ssh
  template:
    src: "{{ ssh_templates_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart sshd
    - wait a few seconds
    - reset connection
  register: result

- name: Print return information from the previous task
  debug:
    var: result
    verbosity: 2

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4
