---

- hosts: syncope,test
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
    #when: ansible_distribution == "Debian" and ansible_distribution_version == "12"

  - name: update repository
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and php packages
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"


